/**
 * Centralized icon configuration for plugin navigation
 * All icons from lucide-react with searchable labels and categories
 */

// Icon definitions with labels and categories for searching
export const ICON_DEFINITIONS = [
  // General
  { value: 'box', label: 'Box', category: 'general' },
  { value: 'cube', label: 'Cube', category: 'general' },
  { value: 'package', label: 'Package', category: 'general' },
  { value: 'archive', label: 'Archive', category: 'general' },
  { value: 'folder', label: 'Folder', category: 'general' },
  { value: 'folder-open', label: 'Folder Open', category: 'general' },
  { value: 'home', label: 'Home', category: 'general' },
  { value: 'settings', label: 'Settings', category: 'general' },
  { value: 'settings-2', label: 'Settings 2', category: 'general' },
  { value: 'sliders', label: 'Sliders', category: 'general' },
  { value: 'wrench', label: 'Wrench', category: 'general' },
  { value: 'tool', label: 'Tool', category: 'general' },
  { value: 'hammer', label: 'Hammer', category: 'general' },

  // Media & Audio
  { value: 'music', label: 'Music', category: 'media' },
  { value: 'music-2', label: 'Music 2', category: 'media' },
  { value: 'music-3', label: 'Music 3', category: 'media' },
  { value: 'music-4', label: 'Music 4', category: 'media' },
  { value: 'headphones', label: 'Headphones', category: 'media' },
  { value: 'speaker', label: 'Speaker', category: 'media' },
  { value: 'volume', label: 'Volume', category: 'media' },
  { value: 'volume-2', label: 'Volume 2', category: 'media' },
  { value: 'mic', label: 'Microphone', category: 'media' },
  { value: 'mic-2', label: 'Microphone 2', category: 'media' },
  { value: 'radio', label: 'Radio', category: 'media' },
  { value: 'podcast', label: 'Podcast', category: 'media' },
  { value: 'disc', label: 'Disc', category: 'media' },
  { value: 'disc-2', label: 'Disc 2', category: 'media' },
  { value: 'disc-3', label: 'Disc 3', category: 'media' },
  { value: 'video', label: 'Video', category: 'media' },
  { value: 'film', label: 'Film', category: 'media' },
  { value: 'clapperboard', label: 'Clapperboard', category: 'media' },
  { value: 'camera', label: 'Camera', category: 'media' },
  { value: 'image', label: 'Image', category: 'media' },
  { value: 'images', label: 'Images', category: 'media' },
  { value: 'picture-in-picture', label: 'Picture in Picture', category: 'media' },
  { value: 'gallery-horizontal', label: 'Gallery', category: 'media' },
  { value: 'play', label: 'Play', category: 'media' },
  { value: 'play-circle', label: 'Play Circle', category: 'media' },

  // Security & Verification
  { value: 'shield', label: 'Shield', category: 'security' },
  { value: 'shield-check', label: 'Shield Check', category: 'security' },
  { value: 'shield-alert', label: 'Shield Alert', category: 'security' },
  { value: 'shield-question', label: 'Shield Question', category: 'security' },
  { value: 'lock', label: 'Lock', category: 'security' },
  { value: 'lock-open', label: 'Lock Open', category: 'security' },
  { value: 'key', label: 'Key', category: 'security' },
  { value: 'key-round', label: 'Key Round', category: 'security' },
  { value: 'fingerprint', label: 'Fingerprint', category: 'security' },
  { value: 'scan', label: 'Scan', category: 'security' },
  { value: 'scan-face', label: 'Scan Face', category: 'security' },
  { value: 'badge-check', label: 'Badge Check', category: 'security' },
  { value: 'check-circle', label: 'Check Circle', category: 'security' },
  { value: 'check-circle-2', label: 'Check Circle 2', category: 'security' },
  { value: 'verified', label: 'Verified', category: 'security' },

  // Development & Code
  { value: 'code', label: 'Code', category: 'development' },
  { value: 'code-2', label: 'Code 2', category: 'development' },
  { value: 'terminal', label: 'Terminal', category: 'development' },
  { value: 'terminal-square', label: 'Terminal Square', category: 'development' },
  { value: 'braces', label: 'Braces', category: 'development' },
  { value: 'brackets', label: 'Brackets', category: 'development' },
  { value: 'git-branch', label: 'Git Branch', category: 'development' },
  { value: 'git-commit', label: 'Git Commit', category: 'development' },
  { value: 'git-merge', label: 'Git Merge', category: 'development' },
  { value: 'git-pull-request', label: 'Git PR', category: 'development' },
  { value: 'bug', label: 'Bug', category: 'development' },
  { value: 'bug-off', label: 'Bug Off', category: 'development' },
  { value: 'puzzle', label: 'Puzzle', category: 'development' },
  { value: 'blocks', label: 'Blocks', category: 'development' },
  { value: 'component', label: 'Component', category: 'development' },

  // Data & Database
  { value: 'database', label: 'Database', category: 'data' },
  { value: 'hard-drive', label: 'Hard Drive', category: 'data' },
  { value: 'server', label: 'Server', category: 'data' },
  { value: 'cloud', label: 'Cloud', category: 'data' },
  { value: 'cloud-download', label: 'Cloud Download', category: 'data' },
  { value: 'cloud-upload', label: 'Cloud Upload', category: 'data' },
  { value: 'download', label: 'Download', category: 'data' },
  { value: 'upload', label: 'Upload', category: 'data' },
  { value: 'file', label: 'File', category: 'data' },
  { value: 'file-text', label: 'File Text', category: 'data' },
  { value: 'file-code', label: 'File Code', category: 'data' },
  { value: 'file-json', label: 'File JSON', category: 'data' },
  { value: 'file-audio', label: 'File Audio', category: 'data' },
  { value: 'file-video', label: 'File Video', category: 'data' },
  { value: 'file-image', label: 'File Image', category: 'data' },
  { value: 'files', label: 'Files', category: 'data' },
  { value: 'save', label: 'Save', category: 'data' },

  // Network & Communication
  { value: 'globe', label: 'Globe', category: 'network' },
  { value: 'globe-2', label: 'Globe 2', category: 'network' },
  { value: 'earth', label: 'Earth', category: 'network' },
  { value: 'wifi', label: 'WiFi', category: 'network' },
  { value: 'signal', label: 'Signal', category: 'network' },
  { value: 'antenna', label: 'Antenna', category: 'network' },
  { value: 'satellite', label: 'Satellite', category: 'network' },
  { value: 'link', label: 'Link', category: 'network' },
  { value: 'link-2', label: 'Link 2', category: 'network' },
  { value: 'unlink', label: 'Unlink', category: 'network' },
  { value: 'share', label: 'Share', category: 'network' },
  { value: 'share-2', label: 'Share 2', category: 'network' },
  { value: 'send', label: 'Send', category: 'network' },
  { value: 'mail', label: 'Mail', category: 'network' },
  { value: 'inbox', label: 'Inbox', category: 'network' },
  { value: 'message-square', label: 'Message', category: 'network' },
  { value: 'message-circle', label: 'Message Circle', category: 'network' },
  { value: 'messages-square', label: 'Messages', category: 'network' },
  { value: 'at-sign', label: 'At Sign', category: 'network' },
  { value: 'hash', label: 'Hash', category: 'network' },

  // AI & Automation
  { value: 'bot', label: 'Bot', category: 'ai' },
  { value: 'brain', label: 'Brain', category: 'ai' },
  { value: 'brain-circuit', label: 'Brain Circuit', category: 'ai' },
  { value: 'brain-cog', label: 'Brain Cog', category: 'ai' },
  { value: 'cpu', label: 'CPU', category: 'ai' },
  { value: 'circuit-board', label: 'Circuit Board', category: 'ai' },
  { value: 'microchip', label: 'Microchip', category: 'ai' },
  { value: 'sparkles', label: 'Sparkles', category: 'ai' },
  { value: 'wand', label: 'Wand', category: 'ai' },
  { value: 'wand-2', label: 'Wand 2', category: 'ai' },
  { value: 'magic', label: 'Magic', category: 'ai' },
  { value: 'lightbulb', label: 'Lightbulb', category: 'ai' },
  { value: 'zap', label: 'Zap', category: 'ai' },
  { value: 'zap-off', label: 'Zap Off', category: 'ai' },
  { value: 'bolt', label: 'Bolt', category: 'ai' },
  { value: 'workflow', label: 'Workflow', category: 'ai' },
  { value: 'waypoints', label: 'Waypoints', category: 'ai' },
  { value: 'repeat', label: 'Repeat', category: 'ai' },
  { value: 'refresh-cw', label: 'Refresh', category: 'ai' },

  // Finance & Crypto
  { value: 'wallet', label: 'Wallet', category: 'finance' },
  { value: 'wallet-2', label: 'Wallet 2', category: 'finance' },
  { value: 'credit-card', label: 'Credit Card', category: 'finance' },
  { value: 'banknote', label: 'Banknote', category: 'finance' },
  { value: 'coins', label: 'Coins', category: 'finance' },
  { value: 'circle-dollar-sign', label: 'Dollar', category: 'finance' },
  { value: 'bitcoin', label: 'Bitcoin', category: 'finance' },
  { value: 'chart-line', label: 'Chart Line', category: 'finance' },
  { value: 'chart-bar', label: 'Chart Bar', category: 'finance' },
  { value: 'chart-pie', label: 'Chart Pie', category: 'finance' },
  { value: 'trending-up', label: 'Trending Up', category: 'finance' },
  { value: 'trending-down', label: 'Trending Down', category: 'finance' },
  { value: 'activity', label: 'Activity', category: 'finance' },
  { value: 'bar-chart', label: 'Bar Chart', category: 'finance' },
  { value: 'bar-chart-2', label: 'Bar Chart 2', category: 'finance' },

  // Animals & Nature
  { value: 'cat', label: 'Cat', category: 'animals' },
  { value: 'dog', label: 'Dog', category: 'animals' },
  { value: 'bird', label: 'Bird', category: 'animals' },
  { value: 'fish', label: 'Fish', category: 'animals' },
  { value: 'bug', label: 'Bug', category: 'animals' },
  { value: 'rabbit', label: 'Rabbit', category: 'animals' },
  { value: 'squirrel', label: 'Squirrel', category: 'animals' },
  { value: 'turtle', label: 'Turtle', category: 'animals' },
  { value: 'paw-print', label: 'Paw Print', category: 'animals' },
  { value: 'leaf', label: 'Leaf', category: 'animals' },
  { value: 'tree-pine', label: 'Pine Tree', category: 'animals' },
  { value: 'trees', label: 'Trees', category: 'animals' },
  { value: 'flower', label: 'Flower', category: 'animals' },
  { value: 'flower-2', label: 'Flower 2', category: 'animals' },
  { value: 'sun', label: 'Sun', category: 'animals' },
  { value: 'moon', label: 'Moon', category: 'animals' },
  { value: 'star', label: 'Star', category: 'animals' },
  { value: 'cloud', label: 'Cloud', category: 'animals' },
  { value: 'snowflake', label: 'Snowflake', category: 'animals' },
  { value: 'flame', label: 'Flame', category: 'animals' },
  { value: 'droplet', label: 'Droplet', category: 'animals' },

  // Users & People
  { value: 'user', label: 'User', category: 'users' },
  { value: 'user-circle', label: 'User Circle', category: 'users' },
  { value: 'user-check', label: 'User Check', category: 'users' },
  { value: 'user-plus', label: 'User Plus', category: 'users' },
  { value: 'users', label: 'Users', category: 'users' },
  { value: 'users-2', label: 'Users 2', category: 'users' },
  { value: 'contact', label: 'Contact', category: 'users' },
  { value: 'contact-2', label: 'Contact 2', category: 'users' },
  { value: 'person-standing', label: 'Person', category: 'users' },
  { value: 'smile', label: 'Smile', category: 'users' },
  { value: 'frown', label: 'Frown', category: 'users' },
  { value: 'skull', label: 'Skull', category: 'users' },
  { value: 'ghost', label: 'Ghost', category: 'users' },

  // Objects
  { value: 'book', label: 'Book', category: 'objects' },
  { value: 'book-open', label: 'Book Open', category: 'objects' },
  { value: 'bookmark', label: 'Bookmark', category: 'objects' },
  { value: 'clipboard', label: 'Clipboard', category: 'objects' },
  { value: 'clipboard-list', label: 'Clipboard List', category: 'objects' },
  { value: 'pen-tool', label: 'Pen', category: 'objects' },
  { value: 'pencil', label: 'Pencil', category: 'objects' },
  { value: 'eraser', label: 'Eraser', category: 'objects' },
  { value: 'scissors', label: 'Scissors', category: 'objects' },
  { value: 'ruler', label: 'Ruler', category: 'objects' },
  { value: 'palette', label: 'Palette', category: 'objects' },
  { value: 'paintbrush', label: 'Paintbrush', category: 'objects' },
  { value: 'brush', label: 'Brush', category: 'objects' },
  { value: 'spray-can', label: 'Spray Can', category: 'objects' },
  { value: 'pipette', label: 'Pipette', category: 'objects' },
  { value: 'compass', label: 'Compass', category: 'objects' },
  { value: 'map', label: 'Map', category: 'objects' },
  { value: 'map-pin', label: 'Map Pin', category: 'objects' },
  { value: 'navigation', label: 'Navigation', category: 'objects' },
  { value: 'clock', label: 'Clock', category: 'objects' },
  { value: 'timer', label: 'Timer', category: 'objects' },
  { value: 'calendar', label: 'Calendar', category: 'objects' },
  { value: 'calendar-days', label: 'Calendar Days', category: 'objects' },
  { value: 'bell', label: 'Bell', category: 'objects' },
  { value: 'bell-ring', label: 'Bell Ring', category: 'objects' },
  { value: 'gift', label: 'Gift', category: 'objects' },
  { value: 'trophy', label: 'Trophy', category: 'objects' },
  { value: 'medal', label: 'Medal', category: 'objects' },
  { value: 'crown', label: 'Crown', category: 'objects' },
  { value: 'gem', label: 'Gem', category: 'objects' },
  { value: 'diamond', label: 'Diamond', category: 'objects' },
  { value: 'heart', label: 'Heart', category: 'objects' },
  { value: 'rocket', label: 'Rocket', category: 'objects' },
  { value: 'plane', label: 'Plane', category: 'objects' },
  { value: 'car', label: 'Car', category: 'objects' },
  { value: 'bike', label: 'Bike', category: 'objects' },
  { value: 'ship', label: 'Ship', category: 'objects' },
  { value: 'anchor', label: 'Anchor', category: 'objects' },

  // Gaming
  { value: 'gamepad', label: 'Gamepad', category: 'gaming' },
  { value: 'gamepad-2', label: 'Gamepad 2', category: 'gaming' },
  { value: 'joystick', label: 'Joystick', category: 'gaming' },
  { value: 'dice-1', label: 'Dice', category: 'gaming' },
  { value: 'target', label: 'Target', category: 'gaming' },
  { value: 'crosshair', label: 'Crosshair', category: 'gaming' },
  { value: 'sword', label: 'Sword', category: 'gaming' },
  { value: 'swords', label: 'Swords', category: 'gaming' },
  { value: 'axe', label: 'Axe', category: 'gaming' },
  { value: 'bomb', label: 'Bomb', category: 'gaming' },
  { value: 'flag', label: 'Flag', category: 'gaming' },
  { value: 'flag-triangle-right', label: 'Flag Triangle', category: 'gaming' },

  // Shapes
  { value: 'circle', label: 'Circle', category: 'shapes' },
  { value: 'square', label: 'Square', category: 'shapes' },
  { value: 'triangle', label: 'Triangle', category: 'shapes' },
  { value: 'hexagon', label: 'Hexagon', category: 'shapes' },
  { value: 'octagon', label: 'Octagon', category: 'shapes' },
  { value: 'pentagon', label: 'Pentagon', category: 'shapes' },
  { value: 'star', label: 'Star', category: 'shapes' },
  { value: 'heart', label: 'Heart', category: 'shapes' },

  // UI Elements
  { value: 'menu', label: 'Menu', category: 'ui' },
  { value: 'grid', label: 'Grid', category: 'ui' },
  { value: 'grid-2x2', label: 'Grid 2x2', category: 'ui' },
  { value: 'grid-3x3', label: 'Grid 3x3', category: 'ui' },
  { value: 'layout', label: 'Layout', category: 'ui' },
  { value: 'layout-dashboard', label: 'Dashboard', category: 'ui' },
  { value: 'layout-grid', label: 'Layout Grid', category: 'ui' },
  { value: 'layout-list', label: 'Layout List', category: 'ui' },
  { value: 'list', label: 'List', category: 'ui' },
  { value: 'list-ordered', label: 'Ordered List', category: 'ui' },
  { value: 'table', label: 'Table', category: 'ui' },
  { value: 'table-2', label: 'Table 2', category: 'ui' },
  { value: 'columns', label: 'Columns', category: 'ui' },
  { value: 'rows', label: 'Rows', category: 'ui' },
  { value: 'sidebar', label: 'Sidebar', category: 'ui' },
  { value: 'panel-left', label: 'Panel Left', category: 'ui' },
  { value: 'panel-right', label: 'Panel Right', category: 'ui' },
  { value: 'panel-top', label: 'Panel Top', category: 'ui' },
  { value: 'panel-bottom', label: 'Panel Bottom', category: 'ui' },
  { value: 'maximize', label: 'Maximize', category: 'ui' },
  { value: 'minimize', label: 'Minimize', category: 'ui' },
  { value: 'expand', label: 'Expand', category: 'ui' },
  { value: 'shrink', label: 'Shrink', category: 'ui' },
  { value: 'filter', label: 'Filter', category: 'ui' },
  { value: 'search', label: 'Search', category: 'ui' },
  { value: 'eye', label: 'Eye', category: 'ui' },
  { value: 'eye-off', label: 'Eye Off', category: 'ui' },

  // Arrows & Navigation
  { value: 'arrow-up', label: 'Arrow Up', category: 'arrows' },
  { value: 'arrow-down', label: 'Arrow Down', category: 'arrows' },
  { value: 'arrow-left', label: 'Arrow Left', category: 'arrows' },
  { value: 'arrow-right', label: 'Arrow Right', category: 'arrows' },
  { value: 'chevron-up', label: 'Chevron Up', category: 'arrows' },
  { value: 'chevron-down', label: 'Chevron Down', category: 'arrows' },
  { value: 'chevron-left', label: 'Chevron Left', category: 'arrows' },
  { value: 'chevron-right', label: 'Chevron Right', category: 'arrows' },
  { value: 'move', label: 'Move', category: 'arrows' },
  { value: 'move-horizontal', label: 'Move Horizontal', category: 'arrows' },
  { value: 'move-vertical', label: 'Move Vertical', category: 'arrows' },
  { value: 'corner-up-left', label: 'Corner Up Left', category: 'arrows' },
  { value: 'corner-up-right', label: 'Corner Up Right', category: 'arrows' },
  { value: 'external-link', label: 'External Link', category: 'arrows' },

  // Status
  { value: 'info', label: 'Info', category: 'status' },
  { value: 'alert-circle', label: 'Alert Circle', category: 'status' },
  { value: 'alert-triangle', label: 'Alert Triangle', category: 'status' },
  { value: 'check', label: 'Check', category: 'status' },
  { value: 'x', label: 'X', category: 'status' },
  { value: 'plus', label: 'Plus', category: 'status' },
  { value: 'minus', label: 'Minus', category: 'status' },
  { value: 'help-circle', label: 'Help', category: 'status' },
  { value: 'ban', label: 'Ban', category: 'status' },
  { value: 'loader', label: 'Loader', category: 'status' },
  { value: 'loader-2', label: 'Loader 2', category: 'status' },
  { value: 'hourglass', label: 'Hourglass', category: 'status' },
];

// Category labels for grouping
export const ICON_CATEGORIES = {
  general: 'General',
  media: 'Media & Audio',
  security: 'Security',
  development: 'Development',
  data: 'Data & Files',
  network: 'Network',
  ai: 'AI & Automation',
  finance: 'Finance',
  animals: 'Animals & Nature',
  users: 'Users',
  objects: 'Objects',
  gaming: 'Gaming',
  shapes: 'Shapes',
  ui: 'UI Elements',
  arrows: 'Arrows',
  status: 'Status',
};

// Get all unique icon values
export const ICON_VALUES = ICON_DEFINITIONS.map(i => i.value);

// Default icon
export const DEFAULT_ICON = 'box';
